### PR TITLE
Adding "_PACKAGE" to naflex.R file

### PR DESCRIPTION
**Pull request by lilyclements**

### CODE REVIEW

**Review by lilyclements — COMMENTED** [review]
@dannyparsons I've made the changes, let me know if you are happy with it. 

Would you like me to update it on CRAN for you? (I assume I can do the source build my end, and put in your details as maintainer etc still)

**Comment by dannyparsons** [comment]
Thanks, that was quick! It looks like my checks are out of date, hence failing. Would you be able to see if you can update them? Maybe on a separate branch. They should just be the standard ones suggested for R packages for testing and package build checks. 

Also, I think the NEWS needs to be updated and the version number? Or is that done at the same time as CRAN submission?

**Comment by dannyparsons** [comment]
Also, I suggest adding yourself to the authors list in DESCRIPTION, maybe with the role `ctb`? As suggested here for patch contribution https://r-pkgs.org/description.html#sec-description-authors-at-r

**Comment by lilyclements** [comment]
@dannyparsons have done all this now - updated checks and code cov files (it looks like it's worked my end - I can't see a fail coming up!), and updated the description and news files

EDIT: I see, I think you need to approve it before I can see if that's fixed the checks problem.

**Comment by dannyparsons** [comment]
Thanks, this looks great! All checks passing now.
If you're about to submit the update to CRAN that would be amazing thank you.

**Pull request merged**
